# Generated by Django 6.0.1 on 2026-01-20 08:05

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_default_user(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    UserProfile = apps.get_model("finance", "UserProfile")

    user, _ = User.objects.get_or_create(
        username="Marti",
        defaults={
            "email": "",
            "first_name": "Marti",
            "last_name": "",
            "password": make_password("12345"),
        },
    )
    user.password = make_password("12345")
    user.save(update_fields=["password"])

    UserProfile.objects.get_or_create(
        user=user,
        defaults={"full_name": "Marti"},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_userprofile_profile_image"),
    ]

    operations = [
        migrations.RunPython(create_default_user, migrations.RunPython.noop),
    ]
